create table FUNCIONARIO
(CPF_FUNCIONARIO number(13) constraint pk_CPF_FUNCIONARIO primary key,
NOME_FUNCIONARIO varchar2(30),
CARGO_FUNCIONARIO varchar2(30),
TEL_FUNCIONARIO varchar2(13),
SALARIO_FUNCIONARIO number(10,3));

INSERT INTO FUNCIONARIO VALUES (123,'CARLA', 'DESENVOLVEDORA', '19-11111', 5550.00);
INSERT INTO FUNCIONARIO VALUES (234,'SUSANA', 'JORNALISTA', '19-55555', 3550.00);
INSERT INTO FUNCIONARIO VALUES (456,'PAOLA', 'DESIGNER', '19-4444444', 4550.00);
INSERT INTO FUNCIONARIO VALUES (567,'JUNIOR', 'ESCRITOR', '19-3333333', 9550.00);
INSERT INTO FUNCIONARIO VALUES (789,'GIOVANNI', 'ELETRICISTA', '19-222222', 2550.00);

create table DEPENDENTE
(COD_DEP number(4) constraint pk_COD_DEP primary key,
NOME_DEP varchar2(30),
FK_CPF_FUNCIONARIO number(13),
FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO));

INSERT INTO DEPENDENTE VALUES (987 ,'CARLAO', 123);


SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPENDENTE;


select FUNCIONARIO.NOME_FUNCIONARIO, DEPENDENTE.NOME_DEP
FROM FUNCIONARIO JOIN DEPENDENTE
on FUNCIONARIO.CPF_FUNCIONARIO = DEPENDENTE.FK_CPF_FUNCIONARIO;


create table CLIENTE
(CPF_CLIENTE number(12) constraint pk_CPF_CLIENTE primary key,
    NOME_CLIENTE varchar2(40),
    ENDERECO_CLIENTE varchar2(30),
    TELEFONE_CLIENTE varchar2(15));
    
    
INSERT INTO CLIENTE VALUES (235 ,'JOSE DO EGITO', 'RUA DA SILVA', '19-1247863');
    
create table PRODUTO
(ID_PRODUTO number(12) constraint pk_ID_PRODUTO primary key,
    NOME_PRODUTO varchar2(40),
    FABRICANTE_PRODUTO varchar2(30),
    PRECO_PRODUTO number(10,2));
    
INSERT INTO PRODUTO VALUES (555 ,'TELEVISAO', 'TELEVICION_COMPANY', 1200.00);
    
create table COMPRA
(ID_COMPRA number(12) constraint pk_ID_COMPRA primary key,
  DATA_COMPRA DATE,
  FORMA_PAGTO_COMPRA varchar2(30),
  CPF_CLIENTE_COMPRA number(12),
  ID_PRODUTO_COMPRA number(12),
  FOREIGN KEY (CPF_CLIENTE_COMPRA) REFERENCES CLIENTE (CPF_CLIENTE),
  FOREIGN KEY (ID_PRODUTO_COMPRA) REFERENCES PRODUTO (ID_PRODUTO));

    
    
INSERT INTO COMPRA VALUES (545 ,'15/09/2025', 'CARTÃO DE CREDITO', 235, 555);


SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPENDENTE;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;
SELECT * FROM COMPRA;


    
    
    
    
    